# Generated by Django 5.0.6 on 2024-07-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObsHex",
            fields=[
                ("Obs_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Hex_Data", models.TextField()),
                ("Obs_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ObsStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_status", models.CharField(max_length=13)),
                ("reset_count", models.IntegerField()),
                ("last_reset_cause", models.IntegerField()),
                (
                    "Obs_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="decoder.obshex"
                    ),
                ),
            ],
        ),
    ]
